name = "shorten-service"
type = "javascript"
account_id = "43db553adafe11377588036999315c17"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "328182c826ed469ebf4b974f4e7cb69b", preview_id = "f0777188b1a74526ae722d64346e7c4e" }
]
